// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/sentinel/sentinel.proto

package sentinel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataMode enumerates the backend behavior modes.
type DataMode int32

const (
	DataMode_DATA_MODE_UNSPECIFIED DataMode = 0
	DataMode_DATA_MODE_NORMAL      DataMode = 1
	DataMode_DATA_MODE_ATTACK      DataMode = 2
	DataMode_DATA_MODE_EXPORT      DataMode = 3
)

// Enum value maps for DataMode.
var (
	DataMode_name = map[int32]string{
		0: "DATA_MODE_UNSPECIFIED",
		1: "DATA_MODE_NORMAL",
		2: "DATA_MODE_ATTACK",
		3: "DATA_MODE_EXPORT",
	}
	DataMode_value = map[string]int32{
		"DATA_MODE_UNSPECIFIED": 0,
		"DATA_MODE_NORMAL":      1,
		"DATA_MODE_ATTACK":      2,
		"DATA_MODE_EXPORT":      3,
	}
)

func (x DataMode) Enum() *DataMode {
	p := new(DataMode)
	*p = x
	return p
}

func (x DataMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sentinel_sentinel_proto_enumTypes[0].Descriptor()
}

func (DataMode) Type() protoreflect.EnumType {
	return &file_proto_sentinel_sentinel_proto_enumTypes[0]
}

func (x DataMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataMode.Descriptor instead.
func (DataMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_sentinel_sentinel_proto_rawDescGZIP(), []int{0}
}

// DataRequest describes what data the client is requesting.
type DataRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// original export path
	Endpoint      string            `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Mode          DataMode          `protobuf:"varint,3,opt,name=mode,proto3,enum=sentinel.DataMode" json:"mode,omitempty"`
	Params        map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_proto_sentinel_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DataRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DataRequest) GetMode() DataMode {
	if x != nil {
		return x.Mode
	}
	return DataMode_DATA_MODE_UNSPECIFIED
}

func (x *DataRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// DataChunk is a single chunk of streamed response data.
type DataChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is the raw bytes of this chunk
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// chunk_index is the 0-based sequence number.
	ChunkIndex int64 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// total_bytes is the cumulative bytes sent so far (server-side count).
	TotalBytes int64 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// is_last indicates this is the final chunk.
	IsLast        bool              `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_proto_sentinel_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *DataChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataChunk) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *DataChunk) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DataChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *DataChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_sentinel_sentinel_proto protoreflect.FileDescriptor

const file_proto_sentinel_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/sentinel/sentinel.proto\x12\bsentinel\"\xe0\x01\n" +
	"\vDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12&\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x12.sentinel.DataModeR\x04mode\x129\n" +
	"\x06params\x18\x04 \x03(\v2!.sentinel.DataRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\tDataChunk\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x03R\n" +
	"chunkIndex\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.sentinel.DataChunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*g\n" +
	"\bDataMode\x12\x19\n" +
	"\x15DATA_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DATA_MODE_NORMAL\x10\x01\x12\x14\n" +
	"\x10DATA_MODE_ATTACK\x10\x02\x12\x14\n" +
	"\x10DATA_MODE_EXPORT\x10\x032F\n" +
	"\vDataService\x127\n" +
	"\aGetData\x12\x15.sentinel.DataRequest\x1a\x13.sentinel.DataChunk0\x01B9Z7github.com/sentinel-proxy/sentinel-proxy/proto/sentinelb\x06proto3"

var (
	file_proto_sentinel_sentinel_proto_rawDescOnce sync.Once
	file_proto_sentinel_sentinel_proto_rawDescData []byte
)

func file_proto_sentinel_sentinel_proto_rawDescGZIP() []byte {
	file_proto_sentinel_sentinel_proto_rawDescOnce.Do(func() {
		file_proto_sentinel_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sentinel_sentinel_proto_rawDesc), len(file_proto_sentinel_sentinel_proto_rawDesc)))
	})
	return file_proto_sentinel_sentinel_proto_rawDescData
}

var file_proto_sentinel_sentinel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sentinel_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sentinel_sentinel_proto_goTypes = []any{
	(DataMode)(0),       // 0: sentinel.DataMode
	(*DataRequest)(nil), // 1: sentinel.DataRequest
	(*DataChunk)(nil),   // 2: sentinel.DataChunk
	nil,                 // 3: sentinel.DataRequest.ParamsEntry
	nil,                 // 4: sentinel.DataChunk.MetadataEntry
}
var file_proto_sentinel_sentinel_proto_depIdxs = []int32{
	0, // 0: sentinel.DataRequest.mode:type_name -> sentinel.DataMode
	3, // 1: sentinel.DataRequest.params:type_name -> sentinel.DataRequest.ParamsEntry
	4, // 2: sentinel.DataChunk.metadata:type_name -> sentinel.DataChunk.MetadataEntry
	1, // 3: sentinel.DataService.GetData:input_type -> sentinel.DataRequest
	2, // 4: sentinel.DataService.GetData:output_type -> sentinel.DataChunk
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sentinel_sentinel_proto_init() }
func file_proto_sentinel_sentinel_proto_init() {
	if File_proto_sentinel_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sentinel_sentinel_proto_rawDesc), len(file_proto_sentinel_sentinel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sentinel_sentinel_proto_goTypes,
		DependencyIndexes: file_proto_sentinel_sentinel_proto_depIdxs,
		EnumInfos:         file_proto_sentinel_sentinel_proto_enumTypes,
		MessageInfos:      file_proto_sentinel_sentinel_proto_msgTypes,
	}.Build()
	File_proto_sentinel_sentinel_proto = out.File
	file_proto_sentinel_sentinel_proto_goTypes = nil
	file_proto_sentinel_sentinel_proto_depIdxs = nil
}
